export const projects = [
  {
    slug: "azure-horizon",
    title: "Azure Horizon",
    year: "2024",
    role: "Fullstack Developer",
    description: "A project management dashboard with real-time collaboration.",
    tags: ["Next.js", "TypeScript", "Tailwind", "Supabase"],
    link: "https://azure-horizon-pm2d.vercel.app/",
    problem: "Teams needed a lightweight way to manage project tasks and see updates in real time without the overhead of bloated enterprise tools.",
    solution: "Built a real-time dashboard using Next.js and Supabase, with instant data sync, clean typography, and a focus on speed over feature bloat.",
    result: "A fast, focused tool that loads in under a second and handles live updates across multiple users without any perceptible lag.",
  },
  {
    slug: "moku",
    title: "Moku",
    year: "2024",
    role: "Frontend Developer",
    description: "A clean, responsive web experience built from scratch.",
    tags: ["HTML", "CSS", "JavaScript"],
    link: "https://jaywon111.github.io/Moku/",
    problem: "The brief was simple: build a site from scratch without frameworks, and make it look and feel modern on every device.",
    solution: "Handcrafted the layout with semantic HTML, modern CSS, and lightweight vanilla JavaScript. Every interaction is intentional and fast.",
    result: "A razor-thin, framework-free site that scores near-perfect on Lighthouse and works flawlessly on any screen.",
  },
  {
    slug: "placeholder-one",
    title: "Project Three",
    year: "2025",
    role: "Fullstack Developer",
    description: "Reserved for the next build. Details to follow.",
    tags: ["Coming Soon"],
    link: "#",
    problem: "Details coming soon.",
    solution: "Details coming soon.",
    result: "Details coming soon.",
  },
  {
    slug: "placeholder-two",
    title: "Project Four",
    year: "2025",
    role: "Fullstack Developer",
    description: "Another reserved slot for future work.",
    tags: ["Coming Soon"],
    link: "#",
    problem: "Details coming soon.",
    solution: "Details coming soon.",
    result: "Details coming soon.",
  },
];
